### ISSUE TITLE
provide a test data file？

### ISSUE THREAD

**Issue by phonogram8384** [marswen/OSU#1]
Can you provide a test data file? I used PIMA to upload diabetes data and reported an error. 
thank you

**Comment by marswen** [comment]
> Can you provide a test data file? I used PIMA to upload diabetes data and reported an error. thank you

It's okay to use the PIMA diabetes data as an example. Could you provide more details about the error, including how to reproduce it?

**Comment by phonogram8384** [comment]
use the test link https://marswen.shinyapps.io/ObservationalStudyUnderstanding/
i upload the test data file .
![image](https://github.com/marswen/OSU/assets/17818808/45f520f2-05e0-4117-8633-d58ec07706f8)
but when click submit button ,the application show error and other tab show same error
![image](https://github.com/marswen/OSU/assets/17818808/e3b72434-ef3a-4148-98da-f5caeb532294)

**Comment by marswen** [comment]
> use the test link https://marswen.shinyapps.io/ObservationalStudyUnderstanding/ i upload the test data file . ![image](https://private-user-images.githubusercontent.com/17818808/345742780-45f520f2-05e0-4117-8633-d58ec07706f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDM2MTgsIm5iZiI6MTcyMDE0MzMxOCwicGF0aCI6Ii8xNzgxODgwOC8zNDU3NDI3ODAtNDVmNTIwZjItMDVlMC00MTE3LTg2MzMtZDU4ZWMwNzcwNmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAxMzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YTBkOGFhYmNjMGYxODdkMGVkYzZjZDQ5ZmM1ODdiYTg0NzQ3OTA5Y2MwNGM1YjRiNjUxNWNjMzlmZjA5ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6v2Qfbh8hISPoZL2XxeUmdhC83gkSOO91n1CI60AunY) but when click submit button ,the application show error and other tab show same error ![image](https://private-user-images.githubusercontent.com/17818808/345743017-e3b72434-ef3a-4148-98da-f5caeb532294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDM2MTgsIm5iZiI6MTcyMDE0MzMxOCwicGF0aCI6Ii8xNzgxODgwOC8zNDU3NDMwMTctZTNiNzI0MzQtZWYzYS00MTQ4LTk4ZGEtZjVjYWViNTMyMjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAxMzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNDEyYzBmZGIwYTk4NzlhNGYyZDYxYTJmMGVhZWM3ZDMzNjYwZDU1OGUyOTk4YTgyZTM5OWQ3NWM1ODc0NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.If8PuI8qg1aYcua6K88s_AIVg70D2fp-wX2Y5jpIlOE)

Have you completed all fields on the study definition page? 
If no variables were selected for the next step, an error will occur. Actually the selected variables, including exposure and outcome variables, are fundamental for epidemic analysis.
